---
# RESPONSIVE VARIABLES
mobile_end_width: 480
tablet_end_width: 768
laptop_end_width: 1450


# SITE VARIABLES
title: MATCHASOFA
url: http://localhost:4000
baseurl: /

disqus_shortname: hmfaysal
share:            true
# Change url to your domain. Leave localhost server or blank when working locally.
# or use the hint from http://jekyllrb.com/docs/github-pages/ to keep this the same
# whether working locally or remotely. Start Jekyll with: jekyll serve --baseurl ''
url:        	  http://localhost:4000


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Asia/Dhaka
future:      true
highlighter: pygments
markdown:    kramdown
paginate:    5
paginate_path: "/blog/page:num"

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /blog/:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class



# other site variables and configs
exclude:
- Gemfile
- Gemfile.lock
- lib
- shopify
assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images
  bundles:
    - 'shared.css'
    - 'shared.js'
    - 'application.css'
    - 'application.js'
  compress:
    css: sass
    js: uglifier
  cachebust: soft
  gzip:
  - text/css
  - application/javascript
